# "C:\\Tableau\\RMT\\Setup\\"

TableauRMTp12_Cert_Source: "C:\\Tableau\\RMT\\Setup\\TableauRMT.p12"
TableauRMTp12_Cert_Destination: "C:\\Tableau\\RMT\\Setup\\TableauRMT.p12"

DigiCertGlobalRootCAcrt_Cert_Source: "C:\\Tableau\\RMT\\Setup\\DigiCertGlobalRootCA.crt"
DigiCertGlobalRootCAcrt_Cert_Destination: "C:\\Tableau\\RMT\\Setup\\DigiCertGlobalRootCA.crt"
