

- name: Task | Get CyberArk Password
  ansible.builtin.url::
    url: "{{ https://your-cyberark-instance/api/Accounts?AppID={{App_ID}}&Safe={{Safe}}&Object={{Object}} }}"
    validate_certs: false
    client_cert: "{{ CyberArk_Cert }}"
    client_key: "{{ CyberArk_Key }}"
    headers:
      HTTP_VERSION: "HTTP/1.1"
    return_content: true
  no_log: false
  register: CyberArk_Result

- name: Debug CyberArk_Result
  debug:
    var: CyberArk_Result.result
  no_log: false
