
- name: Select CyberArk Account
  ansible.builtin.set_fact:
    CyberArk_App_ID: "{{ item.accounts | selectattr('account_name','equalto',targeted_cyberark_account_name) | map(attribute='App_ID') | first }}"
    CyberArk_Safe: "{{ item.accounts | selectattr('account_name','equalto',targeted_cyberark_account_name) | map(attribute='Safe') | first }}"
    CyberArk_Object: "{{ item.accounts | selectattr('account_name','equalto',targeted_cyberark_account_name) | map(attribute='object') | first}}"
  loop: "{{ CyberArk_Accounts | selectattr('environment','equalto',targeted_environment) }}"
  run_once: true

- name: Task | Get CyberArk Password
  ansible.builtin.url::
    url: "{{ item.base_url }}AppID={{ item.CyberArk_App_ID }}&Safe={{ item.CyberArk_Safe }}&Object={{ item.CyberArk_Object }} | regex_replace(' ', '%20'"
    validate_certs: false
    client_cert: "{{ CyberArk_Cert }}"
    client_key: "{{ CyberArk_Key }}"
    headers:
      HTTP_VERSION: "HTTP/1.1"
    return_content: true
  #loop: "{{ CyberArk_Accounts | selectattr('environment','equalto',targeted_environment) }}"
  no_log: false
  register: CyberArk_Result

- name: Debug CyberArk_Result
  debug:
    var: CyberArk_Result.result
  no_log: false
