# "C:\\Tableau\\RMT\\Setup\\"
Tableau_RMT_Master_Location: "C:\\Tableau Resource Monitoring Tool\\Master\\"
Gateway_URL: "https://tableau-initial-server-node-name.company-domain.com/" # Not the Tableau RMT Server.


- name: Tableau RMT MMaster Setup and wait for 60 seconds to complete.
  block:
    - name: Tableau RMT MMaster Setup
      ansible.windows.win_shell: |
        "{{ rmtadmin.cmd master-setup --admin-username={{ hostvars['localhost'].CyberArk_UserName }} --admin-password={{ hostvars['localhost'].CyberArk_Password }} --require-https=true --https-certificate-mode=local --https-certificate-local-name={{ Tableau_RMT_Server_Certificate_Name }} --https-certificate-local-password={{ hostvars['localhost'].CyberArk_Password }} --confirm --verbose
      args: 
        executable: cmd
        chdir: "{{ Tableau_RMT_Master_Location }}"
      register: RMT_Master_Setup
      failed_when: not RMT_Master_Setup.stdout is search(search_phrase) and RMT_Master_Setup.rc != 0
      until: RMT_Master_Setup.stdout is search(search_phrase) or RMT_Master_Setup.stdout is search(search_phrase)
      retries: 5
      delay: 5
      changed_when: RMT_Master_Setup.stdout is search(changed_search_phrase)

  - name: Wait 60 Seconds for Tableau RMT MMaster Setup to complete.
    pause:
      seconds: 60
    when: RMT_Master_Setup.stdout is search(changed_search_phrase)

  - name: Check for existing RMT environments.
    ansible.windows.win_shell: |
      "rmtadmin.cmd environments --verbose"
    args:
      executable: cmd
      chdir: "{{ RMT_Admin_Master_Path}} "
    register: RMT_Environments

  - name: 
    ansible.windows.win_shell: |
      "rmtadmin.cmd create-env --name={{ Tableau_RMT_Environmant_Name }} --gateway-url={{ Gateway_URL }} "
    
    
